#!/usr/bin/env python3
"""Tests for docconv.strip_crawler_extras — removing crawler-generated
summary / "Source" / "Generated by" intro pages and the table-of-contents page
from novel EPUBs (so TTS readers start at chapter 1).

Usage: python tests/test_strip_extras.py        (exit code 1 on failure)
"""
import re
import sys
import tempfile
import zipfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import docconv as dc  # noqa: E402
from lxml import etree  # noqa: E402

XHTML = ('<?xml version="1.0" encoding="utf-8"?><html xmlns="http://www.w3.org/1999/xhtml" '
         'xmlns:epub="http://www.idpf.org/2007/ops"><head><title>t</title></head><body>%s</body></html>')
PROSE = "".join(f"<p>Long story paragraph {j}. Something happens and the hero reacts with courage.</p>" for j in range(25))
tmp = Path(tempfile.mkdtemp(prefix="strip_"))
fails = 0


def build(name, pages, nav=None, ncx=False):
    """pages: [(filename, body_html)] in spine order. nav: filename of the page carrying properties="nav"."""
    p = tmp / name
    with zipfile.ZipFile(p, "w") as z:
        z.writestr("mimetype", "application/epub+zip", compress_type=zipfile.ZIP_STORED)
        z.writestr("META-INF/container.xml", '<?xml version="1.0"?><container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container"><rootfiles><rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/></rootfiles></container>')
        man = sp = ""
        for i, (fn, body) in enumerate(pages):
            z.writestr(f"OEBPS/{fn}", XHTML % body)
            props = ' properties="nav"' if fn == nav else ""
            man += f'<item id="p{i}" href="{fn}" media-type="application/xhtml+xml"{props}/>'
            sp += f'<itemref idref="p{i}"/>'
        if ncx:
            pts = "".join(f'<navPoint id="n{i}"><navLabel><text>{fn}</text></navLabel><content src="{fn}"/></navPoint>' for i, (fn, _) in enumerate(pages))
            z.writestr("OEBPS/toc.ncx", f'<?xml version="1.0"?><ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1"><navMap>{pts}</navMap></ncx>')
            man += '<item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>'
        z.writestr("OEBPS/content.opf", f'<?xml version="1.0"?><package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="u"><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:identifier id="u">x</dc:identifier><dc:title>T</dc:title><dc:language>en</dc:language></metadata><manifest>{man}</manifest><spine>{sp}</spine></package>')
    return p


def spine(p):
    z = zipfile.ZipFile(p)
    opf = etree.fromstring(z.read("OEBPS/content.opf"))
    ns = {"o": "http://www.idpf.org/2007/opf"}
    ids = {i.get("id"): i.get("href") for i in opf.iterfind(".//o:item", ns)}
    return [ids[r.get("idref")] for r in opf.iterfind(".//o:itemref", ns)]


def check(name, cond, info=""):
    global fails
    print(("PASS " if cond else "FAIL ") + name + (f"  {info}" if info else ""))
    if not cond:
        fails += 1


def run(src):
    dst = src.with_name(src.stem + ".out.epub")
    notes = dc.strip_crawler_extras(src, dst)
    return notes, dst


# 1) Lightnovel Crawler layout: cover, intro (id=intro, Summary, Source, Generated by), nav in spine, chapters with footer
toc_html = "<nav epub:type=\"toc\"><h1>Table of Contents</h1><ol><li><a href=\"intro.xhtml\">Intro</a></li>" + \
    "".join(f'<li><a href="chapter-{i}.xhtml">Chapter {i}</a></li>' for i in range(1, 6)) + "</ol></nav>"
pages = [
    ("cover.xhtml", '<img src="cover.jpg" alt="cover"/>'),
    ("intro.xhtml", '<div id="intro"><h1>Reincarnated As A Sword</h1><h3>Author: Yuu Tanaka</h3>'
                    '<p><b>Summary:</b> A man dies and is reborn as a sword in another world.</p>'
                    '<p>Source: https://novelfull.com/reincarnated-as-a-sword</p>'
                    '<p>Generated by Lightnovel Crawler · Made by: BOT @lncrawl_bot</p></div>'),
    ("nav.xhtml", toc_html),
] + [(f"chapter-{i}.xhtml", f"<h1>Chapter {i}: Title</h1>{PROSE}<p class='footer'>Source: https://novelfull.com/ch-{i} — Generated by Lightnovel Crawler</p>") for i in range(1, 6)]
notes, out = run(build("lnc.epub", pages, nav="nav.xhtml", ncx=True))
sp = spine(out)
z = zipfile.ZipFile(out)
c1 = z.read("OEBPS/chapter-1.xhtml").decode()
check("lncrawl: intro + nav removed, cover + all chapters kept", sp == ["cover.xhtml"] + [f"chapter-{i}.xhtml" for i in range(1, 6)], str(sp))
check("lncrawl: chapter footer removed, prose intact", "Generated by" not in c1 and "Source:" not in c1 and c1.count("<p") == 25)
check("lncrawl: nav.xhtml still in package (EPUB3 requires it)", "OEBPS/nav.xhtml" in z.namelist())
check("lncrawl: dangling TOC entries pruned (nav + ncx)",
      "intro.xhtml" not in z.read("OEBPS/nav.xhtml").decode() and "intro.xhtml" not in z.read("OEBPS/toc.ncx").decode())
check("lncrawl: notes returned", len(notes) == 2, str(notes))
check("lncrawl: mimetype first & stored", z.infolist()[0].filename == "mimetype" and z.infolist()[0].compress_type == zipfile.ZIP_STORED)
notes2, out2 = run(out)
check("lncrawl: second pass is a no-op", notes2 == [] and out2.stat().st_size == out.stat().st_size)

# 2) WebToEpub layout: Information page (metadata + Description + Source) and a <ul> toc page without nav property
pages = [
    ("information.xhtml", "<h1>Information</h1><p>Title: My Novel</p><p>Author: Someone</p><p>Status: Ongoing</p>"
                          "<p>Description: A boy finds a ring and goes on an adventure.</p><p>Source: https://example.com/novel</p>"),
    ("toc.xhtml", "<h1>Contents</h1><ul>" + "".join(f'<li><a href="c{i}.xhtml">Chapter {i}</a></li>' for i in range(1, 9)) + "</ul>"),
] + [(f"c{i}.xhtml", f"<h2>Chapter {i}</h2>{PROSE}") for i in range(1, 9)]
notes, out = run(build("webtoepub.epub", pages))
check("webtoepub: info + toc removed", spine(out) == [f"c{i}.xhtml" for i in range(1, 9)], str(spine(out)[:3]))

# 3) Telegram bot flavour: title page with 'Made by BOT' + t.me link + Summary; chapters end with 'Downloaded from'
pages = [("title_page.xhtml", "<h1>Shadow Slave</h1><p>Summary: Growing up in poverty, Sunny never expected anything good.</p>"
                              "<p>Made by: BOT @novelbot · Join t.me/novelchannel</p>")] + \
        [(f"ch{i}.xhtml", f"<h1>Chapter {i} - Nightmare</h1>{PROSE}<div class='footer'><small>Downloaded from https://novelbin.com</small></div>") for i in range(1, 4)]
notes, out = run(build("tgbot.epub", pages))
check("tgbot: title page removed, chapters kept", spine(out) == ["ch1.xhtml", "ch2.xhtml", "ch3.xhtml"], str(spine(out)))
check("tgbot: 'Downloaded from' footer removed", "Downloaded" not in zipfile.ZipFile(out).read("OEBPS/ch1.xhtml").decode())

# 4) Safety: chapter 1 mentions a URL and the word 'source' in prose — must survive
pages = [(f"c{i}.xhtml", f"<h2>Chapter {i}</h2><p>She said the source of the magic was at https://example.com/lore.</p>{PROSE}") for i in range(1, 5)]
notes, out = run(build("safe_url.epub", pages))
check("safety: chapter quoting a URL is untouched", notes == [] and len(spine(out)) == 4, str(notes))

# 5) Safety: real Foreword / Prologue pages (no crawler marks) stay
pages = [("foreword.xhtml", f"<h1>Foreword</h1>{PROSE}"), ("prologue.xhtml", f"<h1>Prologue</h1>{PROSE}"), ("c1.xhtml", f"<h2>Chapter 1</h2>{PROSE}")]
notes, out = run(build("real_book.epub", pages))
check("safety: foreword/prologue kept", notes == [] and spine(out) == ["foreword.xhtml", "prologue.xhtml", "c1.xhtml"])

# 6) Safety: never strip the whole book
pages = [("intro.xhtml", "<p>Generated by Lightnovel Crawler</p><p>Source: https://x.me</p>"), ("c1.xhtml", f"<h2>Chapter 1</h2>{PROSE}")]
notes, out = run(build("tiny.epub", pages))
check("safety: tiny book keeps its one chapter", spine(out) == ["c1.xhtml"], str(spine(out)))

# 7) Safety: chapter 1 that carries a crawler footer but is named like an intro page must NOT be lost
#    (the footer alone is not enough; only real intro pages go)
pages = [("chapter-1.xhtml", f"<h1>Chapter 1</h1>{PROSE}<p>Source: https://x.com — Generated by Lightnovel Crawler</p>"),
         ("chapter-2.xhtml", f"<h1>Chapter 2</h1>{PROSE}")]
notes, out = run(build("footer_only.epub", pages))
check("safety: chapter with footer only loses the footer, not the page", spine(out) == ["chapter-1.xhtml", "chapter-2.xhtml"] and notes and "dropped" in notes[0], str(notes))

print("\nfailures:", fails)
sys.exit(1 if fails else 0)
